"""
Reward Reasoning Model (RRM) Generation & Evaluation Strategy
================================================================

Official paper implementation:
Guo et al. (May 2025): "Reward Reasoning Models" (https://arxiv.org/abs/2505.14674)

How RRM works:
1. **Chain-of-Thought (CoT) Reward Reasoning**:
   Unlike standard scalar reward models, RRM frames reward estimation as a 
   reasoning task. Given a query and candidate responses, RRM autoregressively 
   generates a detailed CoT reasoning trace before producing its final preference 
   judgment in the format `\boxed{Assistant 1}` or `\boxed{Assistant 2}`.
2. **Official Prompt Template**:
   Employs the standardized system and user prompts (Appendix A.1) instructing 
   the model to evaluate instruction fidelity, helpfulness, accuracy, 
   harmlessness, and detail level while mitigating length and position biases.
3. **Official Knockout Tournament (Best-of-N Selection)**:
   For multi-response evaluation, RRM pairs N candidates in a single-elimination 
   bracket requiring O(N) comparisons over log2(N) rounds. In each pairwise match, 
   RRM generates a reasoning trace and selects the winning response to advance.

Usage:
    from benchmarking.strategies.rrm import RRMGenerator
    generator = RRMGenerator(cfg, tokenizer, base_model)
    response, stats = generator.generate(prompt, max_new_tokens=200, return_stats=True)
"""

import re
import time
import logging
from dataclasses import dataclass
from typing import List, Optional, Tuple, Dict, Any

import torch
from transformers import PreTrainedModel, PreTrainedTokenizer

from Model_mechanics.config import SwissKnifeConfig

logger = logging.getLogger(__name__)


# ── Official RRM Prompts (Appendix A.1) ──────────────────────────────────────

RRM_SYSTEM_PROMPT = (
    "You are a helpful assistant in evaluating the quality of the responses for a given instruction.\n"
    "Your goal is to select the best response for the given instruction.\n"
    "Select Assistant 1 or Assistant 2, that is better for the given instruction. The two responses are generated by two different AI assistants respectively.\n"
    "Do NOT say both / neither are good.\n"
    "Here are some rules of the evaluation:\n"
    "(1) If the instruction does not contain harmful content, you should prioritize evaluating whether the output honestly/precisely/closely executes the instruction, then consider its helpfulness, accuracy, level of detail, harmlessness, etc.\n"
    "(2) If the instruction contains harmful content, prioritize the harmlessness and safety of the response.\n"
    "(3) Responses should NOT contain more/less than what the instruction asks for, as such responses do NOT precisely execute the instruction.\n"
    "(4) You should avoid any potential bias and your judgment should be as objective as possible.\n"
    "Here are some potential sources of bias:\n"
    "- The order in which the responses were presented should NOT affect your judgment, as Response A and Response B are equally likely to be the better.\n"
    "- The length of the responses should NOT affect your judgement, as a longer response does not necessarily correspond to a better response. When making your decision, evaluate if the response length is appropriate for the given instruction.\n"
    '(5) Your output should only consist of "\\boxed{Assistant 1}" if assistant 1 is better, or "\\boxed{Assistant 2}" if assistant 2 is better. Omit any other output.'
)

RRM_USER_TEMPLATE = (
    "## Query\n\n"
    "{query}\n\n"
    "## Assistant responses\n\n"
    "### Assistant 1\n\n"
    "{response_1}\n\n"
    "### Assistant 2\n\n"
    "{response_2}\n\n"
    "## Analysis Let's analyze this step by step and decide which assistant is better, and then answer \\boxed{{Assistant 1}} or \\boxed{{Assistant 2}}."
)


@dataclass
class RRMStats:
    """Statistics tracked during RRM generation and tournament selection."""
    strategy: str = "rrm_official"
    total_candidates: int = 0
    tournament_rounds: int = 0
    matches_played: int = 0
    total_time_s: float = 0.0
    reasoning_traces: Optional[List[Dict[str, Any]]] = None

    def to_dict(self) -> dict:
        return {
            "strategy": self.strategy,
            "total_candidates": self.total_candidates,
            "tournament_rounds": self.tournament_rounds,
            "matches_played": self.matches_played,
            "total_time_s": round(self.total_time_s, 3),
            "reasoning_traces": self.reasoning_traces or [],
        }


def parse_rrm_judgment(text: str) -> Optional[int]:
    """
    Parse the official boxed verdict '\\boxed{Assistant 1}' or '\\boxed{Assistant 2}'.
    Returns 1 for Assistant 1, 2 for Assistant 2, or None if unparseable.
    """
    # Direct match for \boxed{Assistant 1} or \boxed{Assistant 2}
    match = re.search(r"\\boxed\{\s*Assistant\s*(1|2)\s*\}", text, re.IGNORECASE)
    if match:
        return int(match.group(1))
    
    # Fallback match without leading backslash
    match_fallback = re.search(r"boxed\{\s*Assistant\s*(1|2)\s*\}", text, re.IGNORECASE)
    if match_fallback:
        return int(match_fallback.group(1))
        
    # Secondary fallback for Assistant 1 vs Assistant 2 near the end of response
    tail = text[-200:]
    if "assistant 1" in tail.lower() and "assistant 2" not in tail.lower():
        return 1
    if "assistant 2" in tail.lower() and "assistant 1" not in tail.lower():
        return 2

    return None


class RRMGenerator:
    """Official Reward Reasoning Model (RRM) Generator & Judge."""

    def __init__(
        self,
        cfg: SwissKnifeConfig,
        tokenizer: PreTrainedTokenizer,
        base_model: PreTrainedModel,
        evaluator_model: Optional[PreTrainedModel] = None,
    ):
        """
        Initialize RRM Generator.

        Args:
            cfg (SwissKnifeConfig): Pipeline config.
            tokenizer (PreTrainedTokenizer): Tokenizer.
            base_model (PreTrainedModel): Generator for candidate responses.
            evaluator_model (PreTrainedModel, optional): Model used for RRM CoT reasoning.
                                                          If None, uses `base_model`.
        """
        self.cfg = cfg
        self.tokenizer = tokenizer
        self.base_model = base_model
        self.evaluator_model = evaluator_model if evaluator_model is not None else base_model
        self.device = next(iter(base_model.parameters())).device

        logger.info(
            "RRMGenerator initialized | Candidates N=%d | Device=%s",
            self.cfg.gsi_n, self.device
        )

    def _format_rrm_prompt(self, query: str, r1: str, r2: str) -> str:
        """Format full prompt with system message and user query/responses."""
        user_content = RRM_USER_TEMPLATE.format(
            query=query.strip(),
            response_1=r1.strip(),
            response_2=r2.strip(),
        )

        messages = [
            {"role": "system", "content": RRM_SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ]

        if hasattr(self.tokenizer, "apply_chat_template"):
            try:
                return self.tokenizer.apply_chat_template(
                    messages, tokenize=False, add_generation_prompt=True
                )
            except Exception:
                pass

        # Manual fallback
        return f"<|im_start|>system\n{RRM_SYSTEM_PROMPT}<|im_end|>\n<|im_start|>user\n{user_content}<|im_end|>\n<|im_start|>assistant\n"

    @torch.no_grad()
    def _evaluate_matches_batch(
        self, query: str, pairs: List[Tuple[str, str]], max_reasoning_tokens: int = 512
    ) -> List[Tuple[int, str]]:
        """
        Run batched RRM pairwise evaluation for all candidate pairs in a round.
        Evaluates all matches in the round simultaneously in a single forward pass.
        """
        if not pairs:
            return []

        prompt_texts = [self._format_rrm_prompt(query, c1, c2) for c1, c2 in pairs]

        # Set tokenizer to left padding for batch generation
        prev_padding_side = self.tokenizer.padding_side
        self.tokenizer.padding_side = "left"

        inputs = self.tokenizer(prompt_texts, return_tensors="pt", padding=True).to(self.device)

        outputs = self.evaluator_model.generate(
            **inputs,
            max_new_tokens=max_reasoning_tokens,
            do_sample=True,
            temperature=0.6,  # Official RRM sampling temperature
            top_p=0.95,
            pad_token_id=self.tokenizer.pad_token_id,
        )

        self.tokenizer.padding_side = prev_padding_side

        input_len = inputs.input_ids.shape[1]
        results = []
        for i in range(len(pairs)):
            gen_tokens = outputs[i, input_len:]
            analysis_output = self.tokenizer.decode(gen_tokens, skip_special_tokens=True)
            winner = parse_rrm_judgment(analysis_output)
            if winner is None:
                winner = 1
            results.append((winner, analysis_output))

        return results

    @torch.no_grad()
    def generate(
        self,
        prompt: str,
        max_new_tokens: Optional[int] = None,
        verbose: bool = False,
        return_stats: bool = False,
    ) -> str | Tuple[str, RRMStats]:
        """
        Generate response using candidate sampling + RRM Knockout Tournament.

        Steps:
        1. Sample N candidate responses from base model.
        2. Execute Knockout Tournament (single elimination over log2 N rounds).
        3. Return champion response.
        """
        max_tokens = max_new_tokens or self.cfg.max_new_tokens
        n = self.cfg.gsi_n

        t_start = time.perf_counter()

        # Step 1: Generate N candidates in memory-safe sub-batches
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.device)
        prefix_len = inputs.input_ids.shape[1]

        if verbose:
            logger.info("RRM: Generating %d candidate responses...", n)

        candidates = []
        gen_batch_size = getattr(self.cfg, "candidate_batch_size", n)  # Full parallel batching on 128GB DGX
        for batch_start in range(0, n, gen_batch_size):
            cur_bs = min(gen_batch_size, n - batch_start)
            sub_batch_ids = inputs.input_ids.expand(cur_bs, -1).contiguous()
            sub_batch_mask = torch.ones_like(sub_batch_ids)

            gen_outputs = self.base_model.generate(
                input_ids=sub_batch_ids,
                attention_mask=sub_batch_mask,
                max_new_tokens=max_tokens,
                do_sample=True,
                temperature=self.cfg.temperature,
                top_k=self.cfg.top_k,
                top_p=self.cfg.top_p,
                pad_token_id=self.tokenizer.pad_token_id,
            )

            for i in range(cur_bs):
                new_tokens = gen_outputs[i, prefix_len:]
                text = self.tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
                candidates.append(text)

        # Step 2: Official RRM Knockout Tournament with Round-Level Match Batching
        current_candidates = list(candidates)
        traces = []
        round_num = 0
        total_matches = 0

        while len(current_candidates) > 1:
            round_num += 1
            next_round_candidates = []
            pairs_to_eval = []
            pair_indices = []

            for i in range(0, len(current_candidates), 2):
                if i + 1 < len(current_candidates):
                    c1 = current_candidates[i]
                    c2 = current_candidates[i + 1]
                    pairs_to_eval.append((c1, c2))
                    pair_indices.append((i, i + 1))

            # Batch evaluate all pairwise matches in this round simultaneously
            eval_results = self._evaluate_matches_batch(
                query=prompt, pairs=pairs_to_eval, max_reasoning_tokens=512
            )

            for idx, ((c1, c2), (winner_idx, reasoning)) in enumerate(zip(pairs_to_eval, eval_results)):
                total_matches += 1
                i1, i2 = pair_indices[idx]
                winner_cand = c1 if winner_idx == 1 else c2
                next_round_candidates.append(winner_cand)

                if verbose:
                    logger.info(
                        "  [Match %d] Round %d | C%d vs C%d | Winner -> Assistant %d",
                        total_matches, round_num, i1 + 1, i2 + 1, winner_idx
                    )

                traces.append({
                    "round": round_num,
                    "match": total_matches,
                    "candidate_1": c1[:100],
                    "candidate_2": c2[:100],
                    "winner": winner_idx,
                    "reasoning_snippet": reasoning[:200],
                })

            if len(current_candidates) % 2 == 1:
                bye_candidate = current_candidates[-1]
                next_round_candidates.append(bye_candidate)
                if verbose:
                    logger.info("  [Bye] Candidate %d advances automatically.", len(current_candidates))

            current_candidates = next_round_candidates

        champion_response = current_candidates[0]
        elapsed = time.perf_counter() - t_start

        if verbose:
            logger.info(
                "RRM Knockout Tournament complete | N=%d | Rounds=%d | Matches=%d | Time=%.2fs",
                n, round_num, total_matches, elapsed
            )

        if not return_stats:
            return champion_response

        stats = RRMStats(
            total_candidates=n,
            tournament_rounds=round_num,
            matches_played=total_matches,
            total_time_s=elapsed,
            reasoning_traces=traces,
        )
        return champion_response, stats
